### ISSUE TITLE
Error while setting up bitvavo platform for sensor

### ISSUE THREAD

**Issue by bakko65** [cyberjunky/home-assistant-bitvavo#6]
Hi Cyberjunky.
I use the Bitvavo integrations to show balance on a nice ESP32 display but it looks like the integration is broken.
I removed the integration and installed it again but it keeps running in an error.
The log shows:   

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:364
integration: Sensor (documentation, issues)
First occurred: 5:30:26 PM (2 occurrences)
Last logged: 5:30:57 PM

Error while setting up bitvavo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/bitvavo/sensor.py", line 35, in async_setup_entry
    entities.append(Balance(coordinator, balance))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bitvavo/sensor.py", line 105, in __init__
    self._get_data_property("asset_value_in_base_asset")
  File "/config/custom_components/bitvavo/sensor.py", line 112, in _get_data_property
    return self.coordinator.data[CONF_BALANCES][self._balance][property_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'asset_value_in_base_asset'



You're code is not touched for a long time, hope you still maintain it?
Hope you can help.

Regards
Herman

**Comment by cyberjunky** [comment]
Hi Herman, It's unmaintained for a long time since I left Bitvavo. Are you sure, you entered the correct configuration values? I'm not even sure how it works anymore. I can have a look but it would be a pain to get working API keys.

**Comment by bakko65** [comment]
Hi Cyberjunky,
The bitvavo is removed from Hacs, probably because of the issue. If you don't use it anymore and I am the only one reporting the issue then it's not the effort to fix it.
Thanks for you're response,
Groet,
Herman

**Comment by cyberjunky** [comment]
@bakko65 perhaps 1.0.3 fixes your issue, I personally don't use Bitvavo anymore.  Even though Hacs doesn't list it by default, you can always add this repository manually.
